# Generated by Django 4.0.3 on 2022-04-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='userperson',
        ),
    ]
