# Generated by Django 4.0.3 on 2022-04-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_rename_users_userperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userperson',
        ),
    ]
