# Generated by Django 4.0.3 on 2022-04-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='subjectName',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
