# Generated by Django 4.0.3 on 2022-04-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_score_subjectname_alter_score_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='time',
        ),
    ]
